# Lab 2 (Numpy) and Lab 3 (Pandas)

In [ ]:
import numpy as np

In [ ]:
# Create a 6 x 6 matrix (array) using random int from 0 to 50
# Number 1:

np.random.seed(100)
random_array = np.random.randint(0,50,36).reshape(6,6)

random_array

array([[ 8, 24,  3, 39, 23, 15],
       [48, 10, 30, 34,  2, 34],
       [14, 34, 49, 48, 24, 15],
       [36, 43, 16,  9, 29, 22],
       [ 2, 27, 44,  4, 31,  1],
       [13, 19, 36,  4, 27,  3]])

In [ ]:
# Using numpy array and indexing select the following subsets ( 3, 30, 49, 16)
# Number 2:
random_array[:4, 2:3]

array([[ 3],
       [30],
       [49],
       [16]])

In [ ]:
# Using numpy array and indexing select the following subsets ( 19, 36, 4, 27)
# Number 3:
random_array[5:,1:5].reshape(-1)

array([19, 36,  4, 27])

In [ ]:
# Using numpy array and indexing select the following subsets (39, 34,  48, 9, 4, 4)
# Number 4:
random_array[:,3:4].reshape(1,-1)

array([[39, 34, 48,  9,  4,  4]])

In [ ]:
# Using numpy array and indexing select the following subsets
# Number 5:
random_array[:3]

array([[ 8, 24,  3, 39, 23, 15],
       [48, 10, 30, 34,  2, 34],
       [14, 34, 49, 48, 24, 15]])

In [ ]:
# Using numpy array and indexing select the following subsets
# Number 6:
random_array[3:,:4]

array([[36, 43, 16,  9],
       [ 2, 27, 44,  4],
       [13, 19, 36,  4]])

In [ ]:
# Using numpy array and indexing select the following subsets
# Number 8:
random_array[:5,2:]

array([[ 3, 39, 23, 15],
       [30, 34,  2, 34],
       [49, 48, 24, 15],
       [16,  9, 29, 22],
       [44,  4, 31,  1]])

In [ ]:
# Using numpy array and indexing select the followng subsets
# Number 9:
random_array[2:5,2:4]

array([[49, 48],
       [16,  9],
       [44,  4]])

In [ ]:
# Using nump array and indexing select the following subsets
# Number 10:
random_array[5:,:4]

array([[13, 19, 36,  4]])

In [ ]:
# Using numpy array and indexing select the following subsets
# Number 11:
random_array[4:5].reshape(-1)

array([ 2, 27, 44,  4, 31,  1])

In [ ]:
# Based from the variable 'random_array', select on numbers that is greater than or equal to 40
# Number 12:

random_array[random_array >= 40]

array([48, 49, 48, 43, 44])

In [ ]:
# Based from the variable 'random_array', reshape the array to 4 x 9
# Number 13:
random_array.reshape(4,9)

array([[ 8, 24,  3, 39, 23, 15, 48, 10, 30],
       [34,  2, 34, 14, 34, 49, 48, 24, 15],
       [36, 43, 16,  9, 29, 22,  2, 27, 44],
       [ 4, 31,  1, 13, 19, 36,  4, 27,  3]])

In [ ]:
# Create the array
# Number 14:
a = np.array([4, -4, 3, 3]).reshape(2,2)
a

array([[ 4, -4],
       [ 3,  3]])

In [ ]:
# Create the array
# Number 15:
b = np.array([4, -5, 1, 7]).reshape(2,2)
b

array([[ 4, -5],
       [ 1,  7]])

In [ ]:
# Create the array
# Number 16:
c = np.array([4, 3, -3, 3, -5, -2, 7, 8, 9]).reshape(3,3)
c

array([[ 4,  3, -3],
       [ 3, -5, -2],
       [ 7,  8,  9]])

In [ ]:
# Create the array
# Number 17:
x = np.array([-1, -2, 4, 3, 4, 1]).reshape(2, 3)
x

array([[-1, -2,  4],
       [ 3,  4,  1]])

In [ ]:
# Create the array
# Number 18:
y = np.array ([5, -6, 7, 8]).reshape(2,2)
y

array([[ 5, -6],
       [ 7,  8]])

In [ ]:
# Number 19
# Based on the creaetd arrays, add a and b
np.add(a,b)

array([[ 8, -9],
       [ 4, 10]])

In [ ]:
# Number 20:
# Based on the created arrays, subtract b to a
np.subtract(b,a)

array([[ 0, -1],
       [-2,  4]])

In [ ]:
# Number 21
# Based on the created arrays, multiply 3 to c
np.multiply(3,c)

array([[ 12,   9,  -9],
       [  9, -15,  -6],
       [ 21,  24,  27]])

In [ ]:
# Number 22
# Based on the created array, is it possible to matrix multiply (dot product) b and c?
# If possible explain , if not possible explain and also why



In [ ]:
# Number 23
# Based on the created array, what is the sum of array x along the columns
np.sum(x, axis = 0)

array([2, 2, 5])

In [ ]:
# Number 24
# Based on the created array, what is the mean of array c along the rows
np.mean(c, axis = 1)

array([ 1.33333333, -1.33333333,  8.        ])

In [ ]:
# Number 25
# Based on the created array, what is the cumsum of array c
np.cumsum(c)

array([ 4,  7,  4,  7,  2,  0,  7, 15, 24])

# Pandas ( Lab Activity )




In [ ]:
import pandas as pd

In [ ]:
# Number 26
# Create the dataframe as variable df, using 20 random integer
np.random.seed(100)
df = pd.DataFrame(np.random.randint(0, 50, (5, 4)), ['R1', 'R2', 'R3', 'R4', 'R5'], ['A', 'B', 'C', 'D'])
df

A   B   C   D
R1   8  24   3  39
R2  23  15  48  10
R3  30  34   2  34
R4  14  34  49  48
R5  24  15  36  43

In [ ]:
# Number 27
# What is the mean of column A
mean_Column_A = df['A'].mean()
mean_Column_A

19.8

In [ ]:
# Number 28
# What is the mean of column R4
mean_R4 = df.loc['R4'].mean()
mean_R4

36.25

In [ ]:
# Number 29
# What is the standard deviation of the column C and Column D?
std_dev = df[['C', 'D']].std()
std_dev

C    23.479779
D    14.788509
dtype: float64

In [ ]:
# Number 30
# Create column E based from the sum of A and C
df['E'] = df['A'] + df['C']
df

A   B   C   D   E
R1   8  24   3  39  11
R2  23  15  48  10  71
R3  30  34   2  34  32
R4  14  34  49  48  63
R5  24  15  36  43  60

In [ ]:
# Number 31
# Select only values from Column E that is greater that 60
result = df[df['E'] > 60][['A', 'C', 'E']]
result

A   C   E
R2  23  48  71
R4  14  49  63

In [ ]:
# Number 31
# Select only values from Column E that is greater than 60 and Column D that is greater than 25
result = df[(df['E'] > 60) & (df['D'] > 25)][['A', 'E', 'D']]
result

A   E   D
R4  14  63  48

In [ ]:
# Number 32
# Using .iloc select the following subset of dataframe
subset = df.iloc[[1, 3, 4], 2:5]
subset

C   D   E
R2  48  10  71
R4  49  48  63
R5  36  43  60

In [ ]:
# Number 33
# Using .iloc select the following subset of dataframe
subset = df.iloc[2:4, 3:]
subset

D   E
R3  34  32
R4  48  63

In [ ]:
# Number 34
# Drop colum E, and assign to a new varauble 'reduced_df'
reduced_df = df.drop('E', axis=1)
reduced_df

A   B   C   D
R1   8  24   3  39
R2  23  15  48  10
R3  30  34   2  34
R4  14  34  49  48
R5  24  15  36  43

In [ ]:
# Number 35
# Drop row R4 and R5 in one line code, and assign to a new variable 'reduced_df_2'
reduced_df_2 = df.drop(['R4', 'R5'], axis=0)
reduced_df_2

A   B   C   D   E
R1   8  24   3  39  11
R2  23  15  48  10  71
R3  30  34   2  34  32