## Numpy Array Indexing and Selection

In [28]:
import numpy as np

In [29]:
new_arr = np.arange(0,16)

In [30]:
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
new_arr[9]

9

In [32]:
new_arr[1:6]

array([1, 2, 3, 4, 5])

In [33]:
new_arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
new_arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [35]:
new_arr[:7] = 100 # NumPy arrays has the ability to broadcast

In [36]:
new_arr

array([100, 100, 100, 100, 100, 100, 100,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [37]:
lst = [1,2,3,4,5]

In [38]:
lst[0:3]  # list cannot broadcast

[1, 2, 3]

## Indexing a 2-D Array (Matrix)

In [39]:
array_2D = np.array([2,4,6,8,10,12,14,16,18])

In [40]:
array_2D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
array_2D = array_2D.reshape(3,3)

In [42]:
array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
# grab the value of 2

array_2D[0,0]

2

In [44]:
# grab the first row

array_2D[0]

array([2, 4, 6])

In [45]:
# grab the value of 16

array_2D[2,1]

16

In [46]:
# selecting sub-matrices

# [4, 6]
# [10, 12]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [47]:
array_2D[:2,1:]

array([[ 4,  6],
       [10, 12]])

In [48]:
# selecting sub-matrices

# [8, 10]
# [14, 16]

In [49]:
array_2D[1:,:2]

array([[ 8, 10],
       [14, 16]])

In [50]:
# selecting sub-matrices

# [4, 6]
# [10, 12]
# [16, 18]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [51]:
array_2D[:,1:]

array([[ 4,  6],
       [10, 12],
       [16, 18]])

In [52]:
# selecting sub-matrices

# [8, 10, 12]
# [14, 16, 18]

array_2D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [53]:
array_2D[1:,:]

array([[ 8, 10, 12],
       [14, 16, 18]])

In [54]:
big_2D_array = np.arange(50).reshape(5,10)

In [55]:
big_2D_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
big_2D_array[2:4,3:8]

array([[23, 24, 25, 26, 27],
       [33, 34, 35, 36, 37]])

## Conditional Selection

In [57]:
another_array = np.arange(1,16)

In [58]:
another_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [59]:
another_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [60]:
bool_array = another_array > 5

In [61]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [62]:
another_array[bool_array]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
another_array[another_array > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

## Matrix Operations

   - addition
   - subtraction
   - scalar multiplication, matrix multiplication, dot
   - division (there is no such thing!)
   
   
$ a = \begin{bmatrix} 3 & -4 \\ 8 & 5 \end{bmatrix}$

$ b = \begin{bmatrix} 9 & -5 \\ 2 & 6 \end{bmatrix}$

$ c = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9\end{bmatrix}$

$ x = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

$ y = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$

In [64]:
a = np.array([3,-4,8,5]).reshape(2,2)
b = np.array([9,-5,2,-6]).reshape(2,2)
c = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [65]:
a

array([[ 3, -4],
       [ 8,  5]])

In [66]:
b

array([[ 9, -5],
       [ 2, -6]])

In [67]:
np.add(a,b)

array([[12, -9],
       [10, -1]])

In [68]:
np.subtract(a,b)

array([[-6,  1],
       [ 6, 11]])

In [69]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a

array([[ 3, -4],
       [ 8,  5]])

In [71]:
np.add(a,c) # cannot add matrix if dimensions are not the same (shape)

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [72]:
# Scalar multiplications

np.multiply(3,a)

array([[  9, -12],
       [ 24,  15]])

In [73]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.array([5,6,7,8]).reshape(2,2)

In [74]:
# The real matrix multiplication (dot product)

np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [75]:
r = np.array([1,2])
s = np.array([1,2]).reshape(2,1)

In [76]:
np.dot(r,s)

array([5])

In [77]:
f = np.array([1,3,5])
g = np.array([1,2,3,4,5,6]).reshape(3,2)

In [78]:
np.dot(f,g)

array([35, 44])

In [79]:
u = np.array([1,2,3,4,5,3]).reshape(3,2)
v = np.array([2,6,4,8]).reshape(2,2)

In [ ]:
np.dot(u,v)